config/routes.rb
Rails.application.routes.draw do

    root to: 'codes#index'
  
  
  # Création de la page Documents pour montrer les différents documents enregistrés en base de données
  get '/documents' => 'documents#index'

  # Pour le post du formulaire d'ajout d'un livre
  post '/documents' => 'documents#create'

  # Création de la page "Codes" pour création du code
  get '/historique' => 'codes#index'
  get '/codes' =>'codes#index'

  # Pour retrouver le doc ou le code seul, par le biais du slug :  url /documents/le_nom_du_doc <-- SLUG
  # ou url /codes/leaseplan_ba
  # Pratique pour les boutons et liens vers les pages
  get 'documents/:slug' => 'documents#show', as: :document

  # Idem Pour afficher le code 
  get 'codes/:slug' => 'codes#show', as: :code

  # Pour devise
  devise_for :users

  # Routes pour les USERS
  get 'user/check'



#Important à conserver pour le dashboard de Administrate. Afin de lui donner les divers onglets du tableau de bord
  namespace :admin do
       
    resources :documents
    resources :codes
 

  
  end
end

app/models/code.rb
class Code < ActiveRecord::Base
	before_save :set_slug
	#action avant enregistrement : aide pour retrouver LE code
	belongs_to :document
	

	
	attr_accessor :image_file_name
	default_scope { order('position DESC')}
	
	# la ligne defaut_url permet de prévoir une image par taille (medium ou thumb) en cas d'image manquante
	# la taille de chaque image est bloquée à 200 x 200 grâce au # après la taille

	# concerne Paperclip et Image Magick pour affichage des vignettes et images 
	has_attached_file :image, styles: { medium: "200x200#", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

	private
		def set_slug
			self.slug = self.client.parameterize
		end




end

app/models/document.rb
class Document < ActiveRecord::Base
	has_many :codes
	
	
	# la ligne defaut_url permet de prévoir une image par taille (medium ou thumb) en cas d'image manquante
	# la taille de chaque image est bloquée à 200 x 200 grâce au # après la taille

	# concerne Paperclip et Image Magick pour affichage des vignettes et images 
	has_attached_file :image, styles: { medium: "200x200#", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_filters.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_filter :authenticate_admin

    def authenticate_admin
      # TODO Add authentication logic here.
    end

    # Par défaut 20 informations par pages
    def records_per_page
       params[:per_page] || 20
    end
  end
end

app/controllers/admin/codes_controller.rb
module Admin
  class CodesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Code.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Code.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/documents_controller.rb
module Admin
  class DocumentsController < Admin::ApplicationController
    
#    def index
#       @documents = Document.all.paginate(10, params[:page])
#    end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Document.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  
end

app/controllers/codes_controller.rb
class CodesController < ApplicationController
  before_action :authenticate_user!

  def index
    # pour la page historique, affiche tous les codes
    @codes = Code.all     
  end

  def create
    Code.create title: params[:title], description: params[:description]
    redirect_to new_admin_code_path
  end

  def show
    # Pour retrouver le code réalisé pour le doc... x. on va le rechercher par le biais du slug.
    @code = Code.find_by(slug: params[:slug])
    
    # Message d'alerte flash si pas de code pour le document
    if @code.nil?
      flash[:notice] = "Aucun code n'a pour l'instant été généré. Souhaitez vous en créé un ?"
      redirect_to new_admin_code_path
    end
  end
 
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :authenticate_user!

  def index
  	@documents = Document.all
  end

  def show
  	#nous devons vérifier que cela ne fonctionne que si un document existe ainsi 
    #que son slug. En cas de cours non-existant --> redirigé sur page d'accueil
  	@document = Document.find_by(slug: params[:slug])
  	if @document.nil?
      flash[:none] = "Le document demandé n'existe pas. Si vous souhaitez son insertion, contactez le service GED."
  		redirect_to root_path
  	end
  end

  def create
    Document.create title: params[:title], description: params[:description], slug: params[:slug]
    redirect_to new_admin_document_path
  end
  
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end

  def login
  end

  def check
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def page_title(title)
		base_title = "G2D2"
		if(title.empty?)
			base_title
		else
			"#{base_title} | #{title}"
		end
	end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/historique_helper.rb
module HistoriqueHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/codes/index.html.erb
<% provide(:title, "Historique") %>
<!-- Permet de donner un nom à la page -->

<!--pour afficher le nombre de cours enregistrés -->
<h1>Historique: <%= @codes.count %> Codes générés</h1>

<div class="jumbotron">
	<div class="row">
	<% for code in @codes %>
		<div class="col-sm-4 col-md-3">
    		<div class="thumbnail">
    		  	<div class="caption">
    			    <h5>Client :</h5><h4><%= code.client %></h4> 
                        <h5>Environnement :</h5> <h4><%= code.environnement %></h4> 
                        <h5>Domaine :</h5> <h4><%= code.domaine %></h4> 
                        <h5>Catégorie Métier :</h5><h4> <%= code.categorie %></h4> 
                        <h5>Statut :</h5> <h4><%= code.statut %></h4>
                        <h5>Image :</h5> <h4><%= code.image %></h4> 
                </div>
    		</div>
  		</div>
	<% end %>
	</div>
</div> <!-- conserver cette div pour entourer les docs de la class jumbotron -->

app/views/codes/show.html.erb
<% provide(:title, "Code") %>
<!-- Permet de donner un nom à la page -->

<!-- Cette page pour voir le code demandé suite page historique -->

<div class="jumbotron">
	<div class="row">

		<div class="col-md-4">
			<div class="caption">
				<h5>Client :</h5><h4><%= code.client %></h4> 
				<h5>Environnement :</h5> <h4><%= code.environnement %></h4> 
				<h5>Domaine :</h5> <h4><%= code.domaine %></h4> 
				<h5>Catégorie Métier :</h5><h4> <%= code.categorie %></h4> 
				<h5>Statut :</h5> <h4><%= code.statut %></h4>
				<h5>Raccourci :</h5> <h4><%= code.slug %></h4> 
			</div>	
		</div>
	</div>
</div>

app/views/documents/index.html.erb
<% provide(:title, "Bibliothèque") %>
<!-- Permet de donner un nom à la page -->

<h1><%= @documents.count%> Documents disponibles </h1>
<h3>Pour consulter les codes réalisés par document, cliquez sur le document concerné.</h3>
<!--pour afficher le nombre de cours enregistrés -->

    <br><hr>

<div class="jumbotron">
	<div class="row">

	<% for document in @documents %>
		<div class="col-sm-6 col-md-4">
    		<div class="thumbnail">
    		  <%= image_tag document.image.url(:medium), alt: document.title%>
    			<div class="caption">
    			    <!-- Ici le lien des titres des documents doivent router sur le doc lui meme. -->
                    <h3><%= link_to document.title, document_path(document.slug)%></h3>


    			    <h5><%= truncate(document.description, length: 150)%></h5>
        <!-- truncate sert à tronquer le message de description à 150 caractères -->
                    <br>
           		</div>
    		</div>
  		</div>	
    <% end %>
	</div>
</div> <!-- conserver cette div pour entourer les docs de la class jumbotron -->

app/views/documents/show.html.erb
<% provide(:title, "Codes du document") %>
<!-- Permet de donner un nom à la page -->

<article>
	<div class="jumbotron">
		<div class="row">
			<div class="col-md-4">
				<h3><%= @document.title%></h3>
			</div>
			<div class="col-md-4">
				<%= image_tag @document.image.url(:medium), alt: "@document.title" %>
			</div>
			<div class="col-md-4">
				<h5><%= @document.description %></h>
			</div>
	</div>
	<hr>
	<p>Ci-dessous les différents codes générés pour ce document.</p>

	<div class="btn btn-success">
  	<%= link_to "Créer un nouveau code",new_admin_code_path %>
  	</div>

<div class="jumbotron">
	<div class="row">

	<section>

	<!-- on peut mettre un message si aucun code n'a été créé pour ce document, pour le moment -->
	<% if @document.codes.empty? %>
		<p>Aucun Code n'a été créé pour ce document.</p>
		<p>Pour en créer un, cliquez sur "Créer un Code".</p>
	<% else %>
	<!-- parcours chacun des codes créés pour ce document et affiche les infos suivantes et tri les par ordre de position-->
		<% @document.codes.order('position').each do |code| %>
			<div class="col-xs-6 col-md-4">

					<div class="caption">

						<h5>Client :</h5><h4><%= code.client %></h4> 
						<h5>Environnement :</h5> <h4><%= code.environnement %></h4> 
						<h5>Domaine :</h5> <h4><%= code.domaine %></h4> 
						<h5>Catégorie Métier :</h5><h4> <%= code.categorie %></h4> 
						<h5>Statut :</h5> <h4><%= code.statut %></h4>
						<h5>Image:</h5> <h4><%= code.image %></h4> 
							
					</div>	
			</div>
		<% end %>
	<% end %>
	</section>
</div>

</article>

app/views/fields/paperclip_field/_form.html.erb
<%= f.label field.attribute %>
<%= f.file_field field.attribute %>

app/views/fields/paperclip_field/_index.html.erb
<%= image_tag field.thumbnail %>

app/views/fields/paperclip_field/_show.html.erb
<%= image_tag field.url %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=page_title(yield(:title))%></title>
<!-- Permet de donner un nom à chaque page -->

	<%= csrf_meta_tag %>
    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

	<!-- partie BOOTSTRAP -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">


	<!-- Liens pour le footer-->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
	<link href="http://cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.css" rel="stylesheet">
</head>

	<!-- les renders concernent les partials cf layouts/partials/_nav et _footer-->

<body>
	<%= render 'layouts/partials/nav' %>
		
	<div class="container" id="police">

<!-- pour affichage du message flash, avec cadre bleu facon bootstrap si l'utilisateur demande l'url avec un doc qui n'existe pas en base (div class alert alert..) ex : /documents/ KJJKJKJ.
CF. controllers/documents_controller.rb:-->

	<%= render 'layouts/partials/flash' %>

	<%= yield %>

	<%= render 'layouts/partials/footer' %>

	</div>

	

	<!-- Bootstrap JavaScript-->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

</body>
</html>

app/views/layouts/partials/_flash.html.erb
<% if flash[:notice] %>
	<div class="alert alert-info">
		<%= flash[:none]%>
	</div>
<%end%>

<% if flash[:none] %>
	<div class="alert alert-info">
		<%= flash[:none]%>
	</div>
<%end%>

<% if flash[:alert] %>
	<div class="alert alert-info">
		<%= flash[:alert]%>
	</div>
<%end%>

app/views/layouts/partials/_footer.html.erb
<link href="http://cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.css" rel="stylesheet">

<footer class="footer">
  <div class="row">

    <div class="small-12 medium-6 large-5 columns">
      <p class="logo"><i class="fi-widget"></i>G2D2</p> 
      <p class="footer-links">
          <%= link_to "Consulter les codes", historique_path%>
          <%= link_to "Consulter les documents", documents_path%>  
      </p>
    </div>

    <div class="small-12 medium-6 large-4 columns">
      <ul class="contact">
        <li><p><i class="fi-marker"></i>Rambouillet 78</p></li>
        <li><p><i class="fi-telephone"></i>+33 6.89.30.15.42</p></li>
        <li><p><i class="fi-mail"></i>alexandra.duval.pro78@gmail.com</p></li>
      </ul>
    </div>

  
    <div class="small-12 medium-12 large-3 columns">
      <ul class="inline-list social">
        <a href="https://twitter.com/Ava78120"><i class="fi-social-twitter"></i></a>
        <a href="https://fr.linkedin.com/in/alexandraduvalroyau"><i class="fi-social-linkedin"></i></a>
        <a href="https://github.com/Ava78"><i class="fi-social-github"></i></a>
      </ul>
    </div>
    <p class="copywrite">&copy; Alexandra DUVAL 2016 All Rights Reserved.</p>
  </div>
</footer>

app/views/layouts/partials/_nav.html.erb
<link href="http://cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.css" rel="stylesheet">

<nav class="menu">

  <h1 class="name"><i class="fi-widget"></i><%= link_to "G2D2", root_path%></h1>

  <ul class="inline-list">
    <li class="active"><%= link_to "Consulter les codes", historique_path%></li>
  </ul>

  <ul class="inline-list">
    <li class="active"><%= link_to "Consulter les documents disponibles", documents_path%></li>
  </ul>


  <ul class="inline-list">
    <li class="active"><%= link_to "Créer un code", new_admin_code_path%></li>
  </ul>



<!--Partie de droite !! -->
  <div class="nav navbar-nav navbar-right">
    <ul class="inline-list">
      <% if user_signed_in? %>
        <li><%=link_to "Déconnexion", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%=link_to "Se Connecter", new_user_session_path%></li>
      <% end %>      
    </ul>    
  </div>
</nav>

		       

app/views/user/check.html.erb
<h1>User#check</h1>
<p>Find me in app/views/user/check.html.erb</p>

app/views/user/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>

app/views/user/login.html.erb
<h1>User#login</h1>
<p>Find me in app/views/user/login.html.erb</p>